apiVersion: v1
kind: Service
metadata:
  namespace: vcare
  name: vcare-frontend-beta
  labels:
    app: vcare-frontend-beta
spec:
  selector:
    app: vcare-frontend-beta
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
      nodePort: 32043
  type: NodePort
